Q_and_A = [['Which planet is known as the Red Planet?', ["Mars", "Venus", "Jupiter", "Saturn"], "Mars"],
           ['Who wrote "Romeo and Juliet"?', ["William Shakespeare", "Jane Austen", "Charles Dickens", "Mark Twain"], "William Shakespeare"],
           ['What is the capital city of France?', ["Paris", "London", "Berlin", "Rome"], "Paris"],
           ['What is the largest mammal in the world?', ["Blue whale", "African elephant", "Giraffe", "Hippopotamus"], "Blue whale"],
           ['Which country is known as the Land of the Rising Sun?', ["Japan", "China", "South Korea", "Thailand"], "Japan"],
           ['What is the tallest mountain in the world?', ["Mount Everest", "K2", "Kangchenjunga", "Lhotse"], "Mount Everest"],
           ['Who painted the Mona Lisa?', ["Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Michelangelo"], "Leonardo da Vinci"],
           ['What is the chemical symbol for water?', ["H2O", "CO2", "NaCl", "O2"], "H2O"],
           ['Who discovered penicillin?', ["Alexander Fleming", "Louis Pasteur", "Marie Curie", "Albert Einstein"], "Alexander Fleming"],
           ['What is the largest organ in the human body?', ["Skin", "Liver", "Brain", "Heart"], "Skin"],
           ['Which country is famous for the Great Wall?', ["China", "India", "Russia", "United States"], "China"],
           ['Who wrote "To Kill a Mockingbird"?', ["Harper Lee", "J.K. Rowling", "Ernest Hemingway", "Stephen King"], "Harper Lee"],
           ['What is the chemical symbol for gold?', ["Au", "Ag", "Fe", "Cu"], "Au"],
           ['Which planet is known as the "Morning Star" or "Evening Star"?', ["Venus", "Mercury", "Mars", "Jupiter"], "Venus"],
           ['Who was the first person to step on the moon?', ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Alan Shepard"], "Neil Armstrong"]]
